# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('subtitle', models.TextField(max_length=200)),
                ('postedBy', models.TextField(max_length=200)),
                ('imgClass', models.TextField(max_length=100)),
                ('content', models.TextField()),
                ('postedAt', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
