# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotToEat', '0003_post_headerimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentId', models.TextField(max_length=100)),
                ('postedBy', models.TextField(max_length=200)),
                ('content', models.TextField()),
                ('postedAt', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(verbose_name='created at')),
                ('like', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField(max_length=100)),
                ('firstName', models.TextField(max_length=200)),
                ('lastName', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='postedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotToEat.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotToEat.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotToEat.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotToEat.Post'),
        ),
    ]
