# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotToEat', '0004_auto_20171226_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalCode', models.TextField(max_length=2)),
                ('name', models.TextField(max_length=200)),
                ('allowedSignup', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.TextField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gotToEat.State'),
            preserve_default=False,
        ),
    ]
